version: '3.7'
services:
  postgres:
    image: postgres
    restart: always
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - data:/var/lib/postgresql/data
  
  pgadmin:
    image: dpage/pgadmin4
    env_file:
      - .env
    ports:
      - "16543:80"
    depends_on:
      - postgres
    logging:
      driver: none

  redis:
    image: redis
    ports:
      - "6379:6379"

  server:
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    depends_on:
      - postgres
      - redis
    networks: 
      - default
    ports:
      - "8080:8080"
volumes:
  data:
